<a href="https://colab.research.google.com/github/redoy722/GNN_Attack/blob/main/Orbit_based_edge_type_generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Install required packages.
import os
import torch
import networkx as nx
import numpy as np
import pandas as pd

os.environ['TORCH'] = torch.__version__
print(torch.__version__)

!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

! pip install deeprobust

2.0.0+cu118
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 25.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 22.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 KB 13.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.4/23.4 MB 53.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 KB 17.1 MB/s eta 0:00:00
  Created wheel for gensim: filename=gensim-3.8.3-cp39-cp39-linux_x86_64.whl size=26527973 sha256=47a552221de3615c07a1495ae1d73352f917641bd014f15ea72afcf21d938782
  Stored in directory: /root/.cache/pip/wheels/ca/5d/af/618594ec2f28608c1d6ee7d2b7e95a3e9b06551e3b80a491d6
Successfully built gensim
  Attempting u

**Modified ORCA Algorithm uploaded to the google drive and run from it**

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
!pip install /content/drive/MyDrive/orca-py2/orca-py  ####### add the path of the orcapy file

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Processing ./drive/MyDrive/orca-py2/orca-py
  Preparing metadata (setup.py) ... done
  Created wheel for orca: filename=orca-1.0-cp39-cp39-linux_x86_64.whl size=259038 sha256=a196bb0f4def8e29d236c1241d5b024e209b8c95cda0a20ff108f9ee9b29b7e8
  Stored in directory: /root/.cache/pip/wheels/e1/c9/7b/b1b626dd74d1f1987fc898c64edbbf74a55200ed0d2ae538cf
Successfully built orca


In [6]:
########### load clean graph  ###########
from deeprobust.graph.data import Dataset, Dpr2Pyg, Pyg2Dpr
Data = Dataset(root='/tmp/', name='cora') 

Loading cora dataset...
Done!
Selecting 1 largest connected components


In [7]:
######### Deepribust data to pyg data conversion for GraphIn Adj
from deeprobust.graph.data import Dataset, Dpr2Pyg, Pyg2Dpr
datapy=Data
pyg_data = Dpr2Pyg(datapy) 
print(pyg_data)

Dpr2Pyg()


Processing...
/usr/local/lib/python3.9/dist-packages/deeprobust/graph/data/pyg_dataset.py:48: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:245.)
  edge_index = torch.LongTensor(dpr_data.adj.nonzero())
Done!


In [8]:
graph_ed=pyg_data[0].edge_index.t()

/usr/local/lib/python3.9/dist-packages/torch_geometric/data/in_memory_dataset.py:157: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)


In [9]:
import numpy
np_graph_ed = graph_ed.numpy()

In [10]:
x=len(pyg_data[0].y)
y=len(np_graph_ed)
xy=[x,y]

In [11]:
with open("graph.in","w") as f:
    f.write("\n".join(" ".join(map(str, x)) for x in (np_graph_ed)))

In [12]:
with open('graph.in', 'r') as file:
    contents = file.read()
    file.close()

with open('graph.in', 'w') as file:
    file.write(' '.join(map(str, xy)))
    file.write("\n")
    file.write(contents)
    file.close()

In [14]:
!python /content/drive/MyDrive/orca-py2/orca-py/test.py   ####### Add the path of the test.py file inside the orcapy file in google colab

graph: Graph with 2485 nodes and 5069 edges
Number of nodes: 2485
Number of graphlets: 73
Counts:  [[5, 50, 8, 2, 157, 149, 436, 5, 3, 20, 43, 4, 1, 1, 0, 939, 433, 534, 661, 2121, 1237, 139, 3403, 1, 77, 112, 85, 31, 63, 159, 17, 308, 400, 2, 6, 17, 4, 75, 6, 13, 30, 3, 2, 15, 0, 11, 3, 2, 32, 1, 0, 1, 4, 1, 0, 0, 4, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0], [6, 15, 9, 6, 137, 51, 11, 5, 1, 8, 18, 8, 2, 5, 2, 493, 468, 63, 988, 195, 43, 43, 3, 1, 115, 11, 22, 42, 27, 145, 31, 5, 12, 2, 1, 10, 10, 0, 2, 3, 0, 4, 6, 5, 0, 8, 21, 2, 22, 0, 0, 3, 0, 1, 0, 1, 1, 7, 2, 5, 3, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 1, 0], [7, 82, 16, 5, 282, 394, 932, 14, 6, 18, 86, 17, 0, 4, 0, 1662, 1369, 1881, 1045, 5804, 4525, 557, 8369, 4, 105, 183, 266, 106, 75, 266, 234, 418, 782, 15, 10, 30, 15, 271, 18, 8, 0, 37, 10, 28, 3, 13, 0, 0, 76, 7, 0, 5, 1, 10, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0], [31, 77, 451, 14, 475, 2184, 77, 4101, 24, 17, 56, 384, 11, 8, 2, 1820, 12791, 2535, 3443, 94

In [15]:
with open('graph.out', 'r') as file:
    data = file.readlines()

In [16]:
int_list = [[int(num) for num in s.strip('[]\n').split(',')] for s in data]
graphlet_features = np.array(int_list)
print(graphlet_features)

[[ 5 50  8 ...  0  0  0]
 [ 6 15  9 ...  0  1  0]
 [ 7 82 16 ...  0  0  0]
 ...
 [ 1  3  0 ...  0  0  0]
 [ 1  3  0 ...  0  0  0]
 [ 1  2  0 ...  0  0  0]]


In [18]:
mylist=[]
for i in range(len(graphlet_features)):
  arr=graphlet_features[i]
  #sorted_arr = np.sort(arr, axis=0)[::-1]
  sorted_indices = np.argsort(arr)[::-1]
  mylist.append([i, sorted_indices[0]])

In [22]:
my_array = np.array(mylist)
df_2d = pd.DataFrame(my_array, columns=['node_number', 'Orbit_type'])

In [24]:
df_2d

node_number  Orbit_type
0               0          22
1               1          18
2               2          22
3               3          21
4               4          18
...           ...         ...
2480         2480          18
2481         2481          22
2482         2482          15
2483         2483          15
2484         2484          15

[2485 rows x 2 columns]

**taking only test node**

In [26]:
from deeprobust.graph.data import Dataset, PrePtbDataset
# load the prognn splits by using setting='prognn'
# because the attacked graphs are generated under prognn splits

data = Dataset(root='/tmp/', name='cora')
adj, features, labels = data.adj, data.features, data.labels
idx_train, idx_val, idx_test = data.idx_train, data.idx_val, data.idx_test

Loading cora dataset...
Selecting 1 largest connected components


In [30]:
######## Taking only Test nodes and convert array to a DataFrame
my_df = pd.DataFrame(idx_test, columns=['node_number'])

In [33]:
onlytest = pd.merge(my_df, df_2d, how='inner', on=['node_number'])

In [34]:
onlytest

node_number  Orbit_type
0            1622          18
1             778          22
2            1117          18
3            2463          15
4             251          18
...           ...         ...
1983          993          15
1984         1157          15
1985         1455          15
1986          298          18
1987         1874          15

[1988 rows x 2 columns]

In [35]:
df_2d=onlytest

In [36]:
counts = df_2d['Orbit_type'].value_counts()
counts

18    637
22    517
15    487
19    259
16     30
21     20
20     10
23      8
32      6
6       3
0       3
17      2
5       2
29      2
24      1
4       1
Name: Orbit_type, dtype: int64

**Extracting Orbit based nodes list**

In [37]:
orbits = {}
for orbit_type, group in df_2d.groupby('Orbit_type'):
    orbits['orbit_'+ str(orbit_type)] = list(group['node_number'])

In [38]:
for key, value in orbits.items():
    print(key + ' = ' + str(value))

orbit_0 = [1845, 1993, 2325]
orbit_4 = [1928]
orbit_5 = [1163, 1049]
orbit_6 = [1754, 2465, 2466]
orbit_15 = [2463, 1496, 348, 1252, 536, 1138, 1899, 1536, 1758, 1488, 271, 867, 114, 219, 545, 297, 603, 2093, 902, 1717, 654, 1642, 520, 1936, 2071, 1003, 951, 689, 847, 404, 1772, 235, 31, 1715, 2289, 203, 862, 233, 1429, 2264, 310, 2122, 2278, 1560, 2237, 1109, 2037, 273, 1332, 679, 859, 126, 1682, 150, 97, 327, 841, 295, 555, 319, 1464, 1842, 1615, 1685, 1526, 2202, 329, 1906, 1101, 95, 2484, 1267, 926, 2159, 611, 1973, 1524, 686, 557, 872, 424, 1409, 1308, 2419, 1920, 650, 2483, 1897, 326, 1489, 331, 636, 1885, 1670, 2334, 1528, 2482, 1293, 1806, 622, 2478, 668, 740, 2020, 612, 2427, 860, 846, 2083, 1796, 2198, 2126, 1698, 486, 2238, 1624, 201, 980, 1558, 896, 678, 1331, 534, 1132, 1275, 2273, 1461, 1795, 878, 1639, 675, 1575, 1802, 1407, 1621, 1016, 717, 2455, 2108, 2188, 2222, 152, 108, 2200, 1512, 619, 653, 1284, 2266, 2398, 322, 2291, 29, 1554, 837, 952, 422, 2452, 12, 2012, 632, 

**Finding the RL states based on the orbit edge pairs**

In [39]:
import itertools

checkList=graph_ed.tolist()

orbit_pairs = {}
compared_orbits = {}

for key, values in orbits.items():
    pair_list = []
    for i in range(len(values)):
        for j in range(i, len(values)):
            pair_list.append([values[i], values[j]])
            if i != j:
                pair_list.append([values[j], values[i]])
    orbit_num = key.split("_")[-1]
    orbit_pair_key = f"orbit_{orbit_num}{orbit_num}"
    orbit_pairs[orbit_pair_key] = pair_list


for orbit1, orbit2 in itertools.product(orbits.keys(), repeat=2):
    if orbit1 < orbit2:
        pair_list = []
        for value1 in orbits[orbit1]:
            for value2 in orbits[orbit2]:
                pair_list.append([value1, value2])
        orbit_nums = orbit1.split("_")[-1] + orbit2.split("_")[-1]
        orbit_pair_key = f"orbit_{orbit_nums}"
        orbit_pairs[orbit_pair_key] = pair_list


for orbit_pair_key, orbit_pair_list in orbit_pairs.items():
    compared_pair_list = []
    for pair in orbit_pair_list:
        if pair in checkList:
            compared_pair_list.append(pair)
        #else:
            #compared_pair_list.append([])

    compared_orbit_key = f"compared_{orbit_pair_key}"
    compared_orbits[compared_orbit_key] = compared_pair_list


In [43]:
print(compared_orbits)

{'compared_orbit_00': [], 'compared_orbit_44': [], 'compared_orbit_55': [], 'compared_orbit_66': [[2465, 2466], [2466, 2465]], 'compared_orbit_1515': [[2463, 1512], [1512, 2463], [1496, 1275], [1275, 1496], [1138, 1137], [1137, 1138], [1536, 675], [675, 1536], [1536, 1554], [1554, 1536], [1536, 92], [92, 1536], [1758, 2037], [2037, 1758], [1758, 2260], [2260, 1758], [1758, 1225], [1225, 1758], [271, 2406], [2406, 271], [867, 1150], [1150, 867], [114, 1576], [1576, 114], [545, 1484], [1484, 545], [2071, 2104], [2104, 2071], [951, 952], [952, 951], [689, 1576], [1576, 689], [847, 843], [843, 847], [1772, 964], [964, 1772], [235, 1687], [1687, 235], [235, 1158], [1158, 235], [31, 1554], [1554, 31], [31, 1292], [1292, 31], [31, 475], [475, 31], [1715, 1558], [1558, 1715], [1715, 2188], [2188, 1715], [1715, 30], [30, 1715], [1715, 26], [26, 1715], [1715, 974], [974, 1715], [2289, 2329], [2329, 2289], [2289, 741], [741, 2289], [2289, 1481], [1481, 2289], [2289, 2292], [2292, 2289], [862, 197

In [44]:
print(compared_orbits['compared_orbit_1515'])

[[2463, 1512], [1512, 2463], [1496, 1275], [1275, 1496], [1138, 1137], [1137, 1138], [1536, 675], [675, 1536], [1536, 1554], [1554, 1536], [1536, 92], [92, 1536], [1758, 2037], [2037, 1758], [1758, 2260], [2260, 1758], [1758, 1225], [1225, 1758], [271, 2406], [2406, 271], [867, 1150], [1150, 867], [114, 1576], [1576, 114], [545, 1484], [1484, 545], [2071, 2104], [2104, 2071], [951, 952], [952, 951], [689, 1576], [1576, 689], [847, 843], [843, 847], [1772, 964], [964, 1772], [235, 1687], [1687, 235], [235, 1158], [1158, 235], [31, 1554], [1554, 31], [31, 1292], [1292, 31], [31, 475], [475, 31], [1715, 1558], [1558, 1715], [1715, 2188], [2188, 1715], [1715, 30], [30, 1715], [1715, 26], [26, 1715], [1715, 974], [974, 1715], [2289, 2329], [2329, 2289], [2289, 741], [741, 2289], [2289, 1481], [1481, 2289], [2289, 2292], [2292, 2289], [862, 1972], [1972, 862], [233, 1148], [1148, 233], [233, 1147], [1147, 233], [310, 2399], [2399, 310], [1560, 1054], [1054, 1560], [2237, 1341], [1341, 2237],

****making every possible pair from orbit lists****

In [46]:
for orbit_pair_key in orbit_pairs.keys():
    #print(f"{orbit_pair_key}: {orbit_pairs[orbit_pair_key]}")
    compared_orbit_key = f"compared_{orbit_pair_key}"
    if len(compared_orbits[compared_orbit_key])> 0: 
      print(f"{compared_orbit_key}: {len(compared_orbits[compared_orbit_key])}")
      print(f"{compared_orbit_key}: {compared_orbits[compared_orbit_key]}")

compared_orbit_66: 2
compared_orbit_66: [[2465, 2466], [2466, 2465]]
compared_orbit_1515: 452
compared_orbit_1515: [[2463, 1512], [1512, 2463], [1496, 1275], [1275, 1496], [1138, 1137], [1137, 1138], [1536, 675], [675, 1536], [1536, 1554], [1554, 1536], [1536, 92], [92, 1536], [1758, 2037], [2037, 1758], [1758, 2260], [2260, 1758], [1758, 1225], [1225, 1758], [271, 2406], [2406, 271], [867, 1150], [1150, 867], [114, 1576], [1576, 114], [545, 1484], [1484, 545], [2071, 2104], [2104, 2071], [951, 952], [952, 951], [689, 1576], [1576, 689], [847, 843], [843, 847], [1772, 964], [964, 1772], [235, 1687], [1687, 235], [235, 1158], [1158, 235], [31, 1554], [1554, 31], [31, 1292], [1292, 31], [31, 475], [475, 31], [1715, 1558], [1558, 1715], [1715, 2188], [2188, 1715], [1715, 30], [30, 1715], [1715, 26], [26, 1715], [1715, 974], [974, 1715], [2289, 2329], [2329, 2289], [2289, 741], [741, 2289], [2289, 1481], [1481, 2289], [2289, 2292], [2292, 2289], [862, 1972], [1972, 862], [233, 1148], [1148